### ISSUE TITLE
test failure: oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Invalid client_id parameter value.

### ISSUE THREAD

**Issue by 0-wiz-0** [requests/requests-oauthlib#203] opened 2015-11-06 11:00 UTC
I've built requests-oauthlib-0.5.0 on NetBSD with python-3.4.3, requests-2.7.0 and oauthlib-1.0.3. When I run the tests, I get:
````
test_web_app_fetch_token (tests.test_oauth2_session.OAuth2SessionTest) ... ok

======================================================================
ERROR: test_fetch_token (tests.test_oauth2_session.OAuth2SessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.4/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/scratch/security/py-requests-oauthlib/work/requests-oauthlib-0.5.0/tests/test_oauth2_session.py", line 134, in test_fetch_token
    self.assertRaises(InvalidRequestError, auth.fetch_token, url)
  File "/usr/pkg/lib/python3.4/unittest/case.py", line 704, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/pkg/lib/python3.4/unittest/case.py", line 162, in handle
    callable_obj(*args, **kwargs)
  File "/scratch/security/py-requests-oauthlib/work/requests-oauthlib-0.5.0/requests_oauthlib/oauth2_session.py", line 203, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/pkg/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/pkg/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/pkg/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 383, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/pkg/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 271, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Invalid client_id parameter value.

----------------------------------------------------------------------
Ran 36 tests in 1.862s

FAILED (errors=1)
*** Error code 1
````

**Comment by Lukasa** [comment] 2015-11-06 15:20
Hmm, I have no idea what the problem here is at the moment. I'll need to dive in and work this one out.

**Comment by Lukasa** [comment] 2015-11-06 17:50
Ok, so I can't reproduce this. Using Python 3.4.3, Requests 2.8.1, and oauthlib 1.0.3 I don't encounter this bug. I also don't reproduce with requests 2.7.0.

Is this steadily reproducible? Or intermittent?

**Comment by 0-wiz-0** [comment] 2015-11-06 21:43
Happens for me reproducibly (3/3 times just now). That's in a sandbox (chroot) on NetBSD-7.99.21/amd64 in case it matters. I've also just upgraded to requests-2.8.1 and still see it.

**Comment by Lukasa** [comment] 2015-11-06 21:43
Hmm. It seems a bit like this is a NetBSD problem. I'll see if I can find a suitable machine.

**Comment by 0-wiz-0** [comment] 2015-11-06 21:44
Let me know if you can't find one and need a test account.

**Comment by Lukasa** [comment] 2015-11-08 09:24
Ah, sorry about this: this is a real bug, but it's fixed in the current master.

**Closed by Lukasa** 2015-11-08 09:24 UTC
