### ISSUE TITLE
TypeError: unorderable types: module() < str()

### ISSUE THREAD

**Issue by HotTabascoSauce** [requests/requests-oauthlib#299] opened 2017-11-09 23:17 UTC
In the __init__.py file there is an if statement that calls `requests.__version__` and compares it to '2.0.0'

I get a type error every time: 
`File "/srv/USER/lib/python3.5/site-packages/requests_oauthlib/__init__.py", line 9, in <module> if requests.__version__ < '2.0.0': 
TypeError: unorderable types: module() < str()`

I was able to manually remove the error by replacing `requests.__version__` with '2.18.4' which is the value it should be pulling. If I run the code in a python terminal, it works, but if I run it as a script it fails.

**Comment by Lukasa** [comment] 2017-11-10 21:52
The fact that it works if you run it in the terminal suggests there is something weird about your script or your script environment. Does it occur in a simple script that only contains the line: `import requests_oauthlib`?

**Comment by sigmavirus24** [comment] 2017-11-12 13:11
A comparison of the following might help:

In your script put at the top:

```py
import requests
print('requests path: {}, requests.version: {}'.format(requests.__file__, requests.__version__))
```

And in your terminal do

```py
>>> import requests
>>> requests.__file__, requests.__version__
```

If they don't match then that will help narrow things down.

**Comment by HotTabascoSauce** [comment] 2017-11-14 03:49
the script returns `requests.version: 2.18.4`

while the one in the terminal returns `'2.18.4'`

they return identical file paths

**Comment by molobrakos** [comment] 2017-12-08 09:53
@Lukasa, is this commit maybe related to this bug?https://github.com/requests/requests/commit/e038aad3ccbd5526346150bd37c8c8a8ee0a0b9b

**Comment by sigmavirus24** [comment] 2017-12-08 18:59
It shouldn't be. That commit was reverted. That said, it does seem similar but this bug report is rather confusing (i.e., it's unclear to me what `I was able to manually remove the error by replacing requests.__version__ with '2.18.4' which is the value it should be pulling.` means). @molobrakos are you reproducing this? Can you share a bit more about how you're reproducing it?

**Comment by molobrakos** [comment] 2017-12-08 20:33
@sigmavirus24, no I am not able to reproduce this in my setup (Ubuntu 16.04). I have developed a plugin/module to Home Assistant (https://home-assistant.io/), and some users report this problem with my module (and with some other modules in Home Assistant also depending on requests-oauthlib: https://github.com/home-assistant/home-assistant/issues/10326#issuecomment-349136500).

I am not 100% sure, but it seems that they all run the Hassbian distribution (https://github.com/home-assistant/pi-gen/releases/tag/v1.31)

**Comment by HotTabascoSauce** [comment] 2017-12-11 15:35
@sigmavirus24, for reference I have requests installed version 2.18.4. If I go into the init file and go to the if statement on line 9 and delete the text `requests.__version__` and replace it with `'2.18.4` then I no longer receive the error.

The variable `requests.__version__` should return '2.18.4' with type str() when called, but for some reason it is returning it as a variable with type module() instead of a variable with type str(). So when the '2.18.4' (type module()) is compared to the '2.0.0' (type str()) it returns a TypeError for comparing a `module()<str()`

This is solved by removing the `requests.__version__` and replacing it with `'2.18.4'` which is interpreted as a str() and then the type error goes away and the rest of the script runs successfully.

**Comment by kasper747** [comment] 2017-12-31 17:00
Same error on Windows 10 with Anaconda 3.

**Comment by singingwolfboy** [comment] 2018-05-20 09:43
Since this issue seems to be related to the `requests` project instead of the `requests-oauthlib`, and it's been several months since there was any interaction on it, I'm going to close the issue. If the problem continues to occur, I suggest filing an issue on the `requests` repository.

**Closed by singingwolfboy** 2018-05-20 09:43 UTC
