### ISSUE TITLE
OAuth2Session refresh token failing when manually doing it via requests succeeds 

### ISSUE THREAD

**Issue by jorwoods** [requests/requests-oauthlib#286] opened 2017-08-28 18:50 UTC
I am working with the Sysomos API, and when I try to use the OAuth2Session object's "refresh token" method, it fails telling me that I am missing a token. I have tried both letting the oauth object use self.token implicitly as well as directly passing it token, per below.

```python

token = oauth.refresh_token(f'https://{domain}/oauth/token', 
                            refresh_token=token['refresh_token'], 
                            params=p2)

---------------------------------------------------------------------------
MissingTokenError                         Traceback (most recent call last)
<ipython-input-36-31891d281fd4> in <module>()
      1 token = oauth.refresh_token(f'https://{domain}/oauth/token', 
      2                             refresh_token=token['refresh_token'],
----> 3                             params=p2)

C:\Anaconda3\envs\py36\lib\site-packages\requests_oauthlib\oauth2_session.py in refresh_token(self, token_url, refresh_token, body, auth, timeout, headers, verify, proxies, **kwargs)
    307             r = hook(r)
    308 
--> 309         self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
    310         if not 'refresh_token' in self.token:
    311             log.debug('No new refresh token given. Re-using old.')

C:\Anaconda3\envs\py36\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py in parse_request_body_response(self, body, scope, **kwargs)
    407         .. _`Section 7.1`: http://tools.ietf.org/html/rfc6749#section-7.1
    408         """
--> 409         self.token = parse_token_response(body, scope=scope)
    410         self._populate_attributes(self.token)
    411         return self.token

C:\Anaconda3\envs\py36\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py in parse_token_response(body, scope)
    374 
    375     params = OAuth2Token(params, old_scope=scope)
--> 376     validate_token_parameters(params)
    377     return params
    378 

C:\Anaconda3\envs\py36\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py in validate_token_parameters(params)
    384 
    385     if not 'access_token' in params:
--> 386         raise MissingTokenError(description="Missing access token parameter.")
    387 
    388     if not 'token_type' in params:

MissingTokenError: (missing_token) Missing access token parameter.
```

However, if I manually try to refresh the token simply using requests:

```python
r = requests.post(f'https://{domain}/oauth/token', 
                  data={'refresh_token':token['refresh_token'],
                 'client_id':p2['client_id'],
                 'client_secret':p2['client_secret'],
                 'grant_type':'refresh_token'})
```

It returns with a response code of 200, along with the new token in the content of the response. 

Am I somehow using the refresh_token method wrong, or is there a bug within it?

**Comment by sahinabi** [comment] 2018-03-01 01:51
i'm having the same problem

**Comment by singingwolfboy** [comment] 2018-05-20 09:53
Unfortunately, there doesn't seem to be enough information here to answer your question. You've provided one line of code that results in an exception:

```python
token = oauth.refresh_token(f'https://{domain}/oauth/token', 
                            refresh_token=token['refresh_token'], 
                            params=p2)
```

But we don't know the state of the `oauth` object, or what is in the `p2` object you're passing to the `params` argument. That makes it almost impossible to understand what is causing the problem here. In the future, please provide a minimal reproducible test case, so that another developer can reproduce the problem that you're seeing. That makes it much easier to understand what the problem is, and debug it.

Since this issue has been open for more than a year without any response, I'm going to close it. If you are still seeking an answer to this question, feel free to reopen the issue and provide a reproducible test case.

**Closed by singingwolfboy** 2018-05-20 09:53 UTC

**Comment by realimpat** [comment] 2018-08-10 02:13
@singingwolfboy @jorwoods I just posted issue 324 which is similar to this, but within fetch_access_token rather than refresh_token. 

I hope I provided enough context so we all can better understand what is going on.
